# Spring Properties
spring:
  application:
     name: client-app
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/client-app/templates/    # Trailing / mandatory
                       # Template location for this application only

# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5 # DO NOT DO THIS IN PRODUCTION

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port

# Map the error path to error template (for Thymeleaf)
error:
  path=/error