# Spring properties
spring:
  application:
     name: riders-service

# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5 # DO NOT DO THIS IN PRODUCTION

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
